### ISSUE TITLE
combining shards into .tfrecord file?

### ISSUE THREAD

**Issue by jannenev** [yeephycho/densenet-tensorflow#5]
I used python build_image_data.py for own data
"../build_image_data.py"
It creates shard files :
train-00000-of-00002
train-00001-of-00002

Now when I run ./train.py it cant find file train.tfrecord
ValueError: Failed to find file: ./own_data_dir/train.tfrecord
This seems to be hardcoded in data_provider.py (line 77) as:
filenames = [os.path.join(DATA_DIR, "train.tfrecord")]

How can I get the code to produce a file named "train.tfrecord" insteald of several separare files, 1 for each shard?

Or is there some other way to combine shard-files to single file named .tfrecord?

**Comment by yeephycho** [comment]
build_image_data.py file, line 87.
